<?php include('layout/header.phtml')?>
		
		<div class="container">
			<div class="row">
				<div class="col s12 m3">
					<div class="card">
						<div class="card-image">
							<img src="http://fakeimg.pl/400x400/">
							<span class="card-title">MD5加密</span>
						</div>
						<div class="card-content">
							線上進行MD5加密
						</div>
						<div class="card-action">
							<a href="/md5">前往</a>
						</div>
					</div>
					
				</div>
				
				<div class="col s12 m3">
					<div class="card">
						<div class="card-image">
							<img src="http://fakeimg.pl/250x100/">
							<span class="card-title">Tools 1</span>
						</div>
						<div class="card-content">
							This is a testestestsetest
						</div>
						<div class="card-action">
							<a href="javascript:;">Action 1</a>
							<a href="javascript:;">Action 2</a>
						</div>
					</div>
					
				</div>
				<div class="col s12 m3">
					<div class="card">
						<div class="card-image">
							<img src="http://fakeimg.pl/250x100/">
							<span class="card-title">Tools 1</span>
						</div>
						<div class="card-content">
							This is a testestestsetest
						</div>
						<div class="card-action">
							<a href="javascript:;">Action 1</a>
							<a href="javascript:;">Action 2</a>
						</div>
					</div>
					
				</div>
				<div class="col s12 m3">
					<div class="card">
						<div class="card-image">
							<img src="http://fakeimg.pl/250x100/">
							<span class="card-title">Tools 1</span>
						</div>
						<div class="card-content">
							This is a testestestsetest
						</div>
						<div class="card-action">
							<a href="javascript:;">Action 1</a>
							<a href="javascript:;">Action 2</a>
						</div>
					</div>
					
				</div>
				<div class="col s12 m3">
					<div class="card">
						<div class="card-image">
							<img src="http://fakeimg.pl/250x100/">
							<span class="card-title">Tools 1</span>
						</div>
						<div class="card-content">
							This is a testestestsetest
						</div>
						<div class="card-action">
							<a href="javascript:;">Action 1</a>
							<a href="javascript:;">Action 2</a>
						</div>
					</div>
					
				</div>
				<div class="col s12 m3">
					<div class="card">
						<div class="card-image">
							<img src="http://fakeimg.pl/250x100/">
							<span class="card-title">Tools 1</span>
						</div>
						<div class="card-content">
							This is a testestestsetest
						</div>
						<div class="card-action">
							<a href="javascript:;">Action 1</a>
							<a href="javascript:;">Action 2</a>
						</div>
					</div>
					
				</div>
				<div class="col s12 m3">
					<div class="card">
						<div class="card-image">
							<img src="http://fakeimg.pl/250x100/">
							<span class="card-title">Tools 1</span>
						</div>
						<div class="card-content">
							This is a testestestsetest
						</div>
						<div class="card-action">
							<a href="javascript:;">Action 1</a>
							<a href="javascript:;">Action 2</a>
						</div>
					</div>
					
				</div>
				<div class="col s12 m3">
					<div class="card">
						<div class="card-image">
							<img src="http://fakeimg.pl/250x100/">
							<span class="card-title">Tools 1</span>
						</div>
						<div class="card-content">
							This is a testestestsetest
						</div>
						<div class="card-action">
							<a href="javascript:;">Action 1</a>
							<a href="javascript:;">Action 2</a>
						</div>
					</div>
					
				</div>
				
			</div>
		</div>

<?php include('layout/footer.phtml')?>
		
		